version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ekspar_backend
    ports:
      - "5050:5000"
    volumes:
      - ./backend:/app
      - ./model:/app/modeldod
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    restart: unless-stopped
