version: '3'
services:
  flask:
    build:
      context: ..
      dockerfile: docker/flask.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../flask-app:/app
    depends_on:
      - opencv
      - yolo

  opencv:
    build:
      context: ..
      dockerfile: docker/opencv.Dockerfile
    volumes:
      - ../opencv:/app

  yolo:
    build:
      context: ..
      dockerfile: docker/yolo.Dockerfile
    volumes:
      - ../yolo:/app
