version: '3'
services:

  tailscale:
    image: tailscale/tailscale
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    command: tailscaled
    
  flask:
    build:
      context: ..
      dockerfile: docker/flask.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../flask-app:/app
    restart: always
    depends_on:
      - opencv
      - yolo

  opencv:
    build:
      context: ..
      dockerfile: docker/opencv.Dockerfile
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true

    ports:
      - "5001:5001"  # OpenCV läuft auf 5001
    restart: always

  yolo:
    build:
      context: ..
      dockerfile: docker/yolo.Dockerfile
    ports:
      - "5002:5002"  # YOLO bekommt nun eine API auf 5002
    restart: always
